trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Install and Build'

- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    containerRegistry: 'DockerHubConnection'  # Use the name of the Docker Hub service connection
    repository: 'pruebamobiletec'
    command: build
    Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    tags: 'latest'

- script: docker login --username $(DOCKER_USERNAME) --password $(DOCKER_PASSWORD)
  displayName: 'Docker Login'

- script: docker push nicollemayol/pruebamobiletec:latest
  displayName: 'Push Docker Image'

